/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TikTrixFirstComeAirdrop } from "./TikTrixFirstComeAirdrop";
export type { TikTrixManualAirdrop } from "./TikTrixManualAirdrop";
