/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tiktrixAirdrop from "./tiktrix-airdrop";
export type { tiktrixAirdrop };
import type * as vesting from "./vesting";
export type { vesting };
