/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Mintable } from "./IERC20Mintable";
export type { TikTrixGameReward } from "./TikTrixGameReward";
