/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenERC20 } from "./ITokenERC20";
export type { TikTrixGameReward } from "./TikTrixGameReward";
