/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { TikTrixGameReward__factory } from "./TikTrixGameReward__factory";
