/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITokenERC20__factory } from "./ITokenERC20__factory";
export { TikTrixGameReward__factory } from "./TikTrixGameReward__factory";
