/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VestingWalletReferralFactory } from "./VestingWalletReferralFactory";
export type { VestingWalletReferralUpgradeable } from "./VestingWalletReferralUpgradeable";
