/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBurnableERC20 } from "./IBurnableERC20";
export type { IContractMetadata } from "./IContractMetadata";
export type { IMintableERC20 } from "./IMintableERC20";
export type { IMulticall } from "./IMulticall";
export type { IOwnable } from "./IOwnable";
export type { IPermissions } from "./IPermissions";
export type { IPermissionsEnumerable } from "./IPermissionsEnumerable";
