/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TikTrixFirstComeAirdrop__factory } from "./TikTrixFirstComeAirdrop__factory";
export { TikTrixManualAirdrop__factory } from "./TikTrixManualAirdrop__factory";
