/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface VestingWalletCommonFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createVestingWallet"
      | "executeUpgrade"
      | "getAllProposalIds"
      | "getAllSigners"
      | "getImplementation"
      | "getUpgradeProposal"
      | "hasSignedProposal"
      | "owner"
      | "proposalIds"
      | "proposeUpgrade"
      | "renounceOwnership"
      | "requiredSignatures"
      | "signUpgrade"
      | "signerCount"
      | "signers"
      | "signersList"
      | "timelockDuration"
      | "transferOwnership"
      | "upgradeProposals"
      | "vestingImplementation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ImplementationUpgraded"
      | "OwnershipTransferred"
      | "UpgradeExecuted"
      | "UpgradeProposed"
      | "UpgradeSigned"
      | "VestingWalletCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createVestingWallet",
    values: [
      string,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProposalIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUpgradeProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignedProposal",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeUpgrade",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredSignatures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signersList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeProposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createVestingWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProposalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpgradeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSignedProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signersList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingImplementation",
    data: BytesLike
  ): Result;
}

export namespace ImplementationUpgradedEvent {
  export type InputTuple = [
    oldImplementation: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    oldImplementation: string,
    newImplementation: string
  ];
  export interface OutputObject {
    oldImplementation: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeExecutedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    vestingWallet: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    proposalId: string,
    vestingWallet: string,
    newImplementation: string
  ];
  export interface OutputObject {
    proposalId: string;
    vestingWallet: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeProposedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    vestingWallet: AddressLike,
    newImplementation: AddressLike,
    proposer: AddressLike
  ];
  export type OutputTuple = [
    proposalId: string,
    vestingWallet: string,
    newImplementation: string,
    proposer: string
  ];
  export interface OutputObject {
    proposalId: string;
    vestingWallet: string;
    newImplementation: string;
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeSignedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    signer: AddressLike,
    totalSignatures: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    signer: string,
    totalSignatures: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    signer: string;
    totalSignatures: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingWalletCreatedEvent {
  export type InputTuple = [
    vestingWallet: AddressLike,
    beneficiary: AddressLike,
    token: AddressLike,
    interval: BigNumberish,
    totalPhases: BigNumberish,
    amountPerPhase: BigNumberish,
    startTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    vestingWallet: string,
    beneficiary: string,
    token: string,
    interval: bigint,
    totalPhases: bigint,
    amountPerPhase: bigint,
    startTimestamp: bigint
  ];
  export interface OutputObject {
    vestingWallet: string;
    beneficiary: string;
    token: string;
    interval: bigint;
    totalPhases: bigint;
    amountPerPhase: bigint;
    startTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VestingWalletCommonFactory extends BaseContract {
  connect(runner?: ContractRunner | null): VestingWalletCommonFactory;
  waitForDeployment(): Promise<this>;

  interface: VestingWalletCommonFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVestingWallet: TypedContractMethod<
    [
      contractURI: string,
      beneficiary: AddressLike,
      tokenAddress: AddressLike,
      interval: BigNumberish,
      totalPhases: BigNumberish,
      amountPerPhase: BigNumberish,
      startTimestamp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  executeUpgrade: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  getAllProposalIds: TypedContractMethod<[], [string[]], "view">;

  getAllSigners: TypedContractMethod<[], [string[]], "view">;

  getImplementation: TypedContractMethod<[], [string], "view">;

  getUpgradeProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        vestingWallet: string;
        newImplementation: string;
        signatures: bigint;
        proposedAt: bigint;
        executed: boolean;
        canExecute: boolean;
      }
    ],
    "view"
  >;

  hasSignedProposal: TypedContractMethod<
    [proposalId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  proposeUpgrade: TypedContractMethod<
    [vestingWallet: AddressLike, newImplementation: AddressLike],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requiredSignatures: TypedContractMethod<[], [bigint], "view">;

  signUpgrade: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  signerCount: TypedContractMethod<[], [bigint], "view">;

  signers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  signersList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  timelockDuration: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeProposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        vestingWallet: string;
        newImplementation: string;
        signatures: bigint;
        proposedAt: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  vestingImplementation: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVestingWallet"
  ): TypedContractMethod<
    [
      contractURI: string,
      beneficiary: AddressLike,
      tokenAddress: AddressLike,
      interval: BigNumberish,
      totalPhases: BigNumberish,
      amountPerPhase: BigNumberish,
      startTimestamp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeUpgrade"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllProposalIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUpgradeProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        vestingWallet: string;
        newImplementation: string;
        signatures: bigint;
        proposedAt: bigint;
        executed: boolean;
        canExecute: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSignedProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proposeUpgrade"
  ): TypedContractMethod<
    [vestingWallet: AddressLike, newImplementation: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredSignatures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signUpgrade"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "signersList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "timelockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeProposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        vestingWallet: string;
        newImplementation: string;
        signatures: bigint;
        proposedAt: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vestingImplementation"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ImplementationUpgraded"
  ): TypedContractEvent<
    ImplementationUpgradedEvent.InputTuple,
    ImplementationUpgradedEvent.OutputTuple,
    ImplementationUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeExecuted"
  ): TypedContractEvent<
    UpgradeExecutedEvent.InputTuple,
    UpgradeExecutedEvent.OutputTuple,
    UpgradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeProposed"
  ): TypedContractEvent<
    UpgradeProposedEvent.InputTuple,
    UpgradeProposedEvent.OutputTuple,
    UpgradeProposedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeSigned"
  ): TypedContractEvent<
    UpgradeSignedEvent.InputTuple,
    UpgradeSignedEvent.OutputTuple,
    UpgradeSignedEvent.OutputObject
  >;
  getEvent(
    key: "VestingWalletCreated"
  ): TypedContractEvent<
    VestingWalletCreatedEvent.InputTuple,
    VestingWalletCreatedEvent.OutputTuple,
    VestingWalletCreatedEvent.OutputObject
  >;

  filters: {
    "ImplementationUpgraded(address,address)": TypedContractEvent<
      ImplementationUpgradedEvent.InputTuple,
      ImplementationUpgradedEvent.OutputTuple,
      ImplementationUpgradedEvent.OutputObject
    >;
    ImplementationUpgraded: TypedContractEvent<
      ImplementationUpgradedEvent.InputTuple,
      ImplementationUpgradedEvent.OutputTuple,
      ImplementationUpgradedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpgradeExecuted(bytes32,address,address)": TypedContractEvent<
      UpgradeExecutedEvent.InputTuple,
      UpgradeExecutedEvent.OutputTuple,
      UpgradeExecutedEvent.OutputObject
    >;
    UpgradeExecuted: TypedContractEvent<
      UpgradeExecutedEvent.InputTuple,
      UpgradeExecutedEvent.OutputTuple,
      UpgradeExecutedEvent.OutputObject
    >;

    "UpgradeProposed(bytes32,address,address,address)": TypedContractEvent<
      UpgradeProposedEvent.InputTuple,
      UpgradeProposedEvent.OutputTuple,
      UpgradeProposedEvent.OutputObject
    >;
    UpgradeProposed: TypedContractEvent<
      UpgradeProposedEvent.InputTuple,
      UpgradeProposedEvent.OutputTuple,
      UpgradeProposedEvent.OutputObject
    >;

    "UpgradeSigned(bytes32,address,uint256)": TypedContractEvent<
      UpgradeSignedEvent.InputTuple,
      UpgradeSignedEvent.OutputTuple,
      UpgradeSignedEvent.OutputObject
    >;
    UpgradeSigned: TypedContractEvent<
      UpgradeSignedEvent.InputTuple,
      UpgradeSignedEvent.OutputTuple,
      UpgradeSignedEvent.OutputObject
    >;

    "VestingWalletCreated(address,address,address,uint64,uint64,uint256,uint64)": TypedContractEvent<
      VestingWalletCreatedEvent.InputTuple,
      VestingWalletCreatedEvent.OutputTuple,
      VestingWalletCreatedEvent.OutputObject
    >;
    VestingWalletCreated: TypedContractEvent<
      VestingWalletCreatedEvent.InputTuple,
      VestingWalletCreatedEvent.OutputTuple,
      VestingWalletCreatedEvent.OutputObject
    >;
  };
}
