/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VestingWalletReferralFactory__factory } from "./VestingWalletReferralFactory__factory";
export { VestingWalletReferralUpgradeable__factory } from "./VestingWalletReferralUpgradeable__factory";
