/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vestingWalletAdvisorsSol from "./VestingWalletAdvisors.sol";
export type { vestingWalletAdvisorsSol };
import type * as vestingWalletCommunitySol from "./VestingWalletCommunity.sol";
export type { vestingWalletCommunitySol };
import type * as vestingWalletMarketingSol from "./VestingWalletMarketing.sol";
export type { vestingWalletMarketingSol };
import type * as vestingWalletNodeSol from "./VestingWalletNode.sol";
export type { vestingWalletNodeSol };
import type * as vestingWalletReferralSol from "./VestingWalletReferral.sol";
export type { vestingWalletReferralSol };
export type { VestingWallet } from "./VestingWallet";
export type { VestingWalletCliff } from "./VestingWalletCliff";
