/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VestingWallet } from "./VestingWallet";
export type { VestingWalletAdvisors } from "./VestingWalletAdvisors";
export type { VestingWalletCliff } from "./VestingWalletCliff";
export type { VestingWalletCommunity } from "./VestingWalletCommunity";
export type { VestingWalletMarketing } from "./VestingWalletMarketing";
export type { VestingWalletNode } from "./VestingWalletNode";
export type { VestingWalletReferral } from "./VestingWalletReferral";
